### PR TITLE
NAS-133288 / 25.04 / remove unnecessary dependency

### PR DESCRIPTION
**Pull request by yocalebo**
As pointed out by a really ungracious, rude user @wongsyrone. They called me a "stupid author" (Cf. [here](https://github.com/wongsyrone/truenas-scale-middleware/commit/2d7e8b33018d9a119e29109e696ce095446bfc87) and claimed that updates no longer worked, when in reality, they probably don't know what they're really doing since `psutil` isn't even used in this code. I find it ironic their GitHub profile says "amateur programmer working for traditional industry/talk is cheap, no code to show" but also call other programmers "stupid". Weird way to insult someone. Either way, I'll remove this as a dependency since it's not actually used.

### CODE REVIEW

**Comment by wongsyrone** [comment]
Sorry, but you change another unrelated repo again. What I mean is https://github.com/truenas/scale-build/blob/master/truenas_install/__main__.py#L17

**Comment by wongsyrone** [comment]
BTW, it's really braindead to lock PR after being merged in iXSystem, which makes GitHub purely a private issue tracker for your company, leaving no space for bug reporting and making conversation regarding bugs or issues for coders.

**Comment by yocalebo** [comment]
> BTW, it's really braindead to lock PR after being merged in iXSystem, which makes GitHub purely a private issue tracker for your company, leaving no space for bug reporting and making conversation regarding bugs or issues for coders.

It's not braindead, it's called process. We ask that community users submit bug issues through Jira. That's where the entire company works on issues. If you can't even do that, then you've got issues we can't solve.

**Comment by wongsyrone** [comment]
I submitted using Jira before, the triage team just closed the issue and doesn't even care what I wrote.

**Comment by yocalebo** [comment]
> Sorry, but you change another unrelated repo again. What I mean is https://github.com/truenas/scale-build/blob/master/truenas_install/__main__.py#L17

Oh wow, you mean you're actually contributing to the project in a meaningful way instead of devolving to ad-hominem? See how much easier that was to tell me what you were actually talking about instead of reverting to personal insults?

**Comment by yocalebo** [comment]
> I submitted using Jira before, the triage team just closed the issue and doesn't even care what I wrote.

That's a weird way to justify calling a core member  "stupid" for a free product that you use.

**Comment by wongsyrone** [comment]
I saw the Jira tickets are closed. I'm feeling you are angry.

**Review by mgrimesix — APPROVED** [review]
It can be hard to not get snippy with arrogant users.

**Pull request merged**
